version = 1

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_root = "github.com/krakendio/krakend-jsonschema"

[[transformers]]
name = "gofmt"
enabled = true

[[transformers]]
name = "gofumpt"
enabled = true